### ISSUE TITLE
`deps` and `build-deps` from `info.rkt` seem to be ignored??

### ISSUE THREAD

**Issue by greghendershott** [Bogdanp/setup-racket#15]
I'm doing a fire drill to switch from Travis CI to GitHub Actions, across a half dozen projects.

Your `setup-racket` action is great -- thank you!

It's already worked for me on a couple projects, such as [`sha`](https://github.com/greghendershott/sha) and [`http`](https://github.com/greghendershott/http), which don't in turn depend on any of my other projects.

But now I'm updating [`aws`](https://github.com/greghendershott/sha), which depends on both of those. The `aws` `info.rkt`:

```racket
#lang info
(define version "1.15")
(define collection 'multi)
(define deps '(["base" #:version "6.3"]
               ["http" #:version "0.3"]
               "sha"))
(define build-deps '("at-exp-lib"
                     "racket-doc"
                     "rackunit-lib"
                     "scribble-lib"))
```

And I'm finding it is failing to install the `sha` and `http` deps with the usual

    raco pkg install --auto --link aws

Run locally, or on Travis CI, the `--auto` means that `sha` and `http` would be installed.

But not when run on GH Actions. `raco pkg install` acts as if the deps don't exist (?!?).

Instead I need to add an extra, "hack" step:

```yaml
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket_version:
          - '6.9'
          - '7.9'
          - 'current'
        include:
          - racket_version: 'current'
            allow_failure: true
    name: Test Racket ${{ matrix.racket_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: 'x64'
          distribution: 'full'
          version: ${{ matrix.racket_version }}
      # This next step should not be necessary: The step after it --
      # `raco pkg install --auto` ought to install `deps` and
      # `build-deps` from aws/info.rkt. And e.g. that used to work on
      # Travis CI. Why is it not working with Bogdanp/setup-racket --
      # I am stumped??? This hack is similar to using the `packages:`
      # field, but that barfs before Racket 7.4 due to using
      # --no-docs. Anyway, I don't like that, either, because it means
      # duplicating dependency information in info.rkt and here, which
      # is bad.
      - name: Install Dependencies b/c info.rkt deps being ignored
        run: raco pkg install --auto sha http
      - name: Install Package
        run: raco pkg install --auto --link aws
      - name: Run Tests
        run: raco test -x -p aws
```

Do you have any idea what's going on here? I must be doing something dumb, to cause this issue.

Meanwhile the hack "works". I just don't love it as a general solution because it's not DRY and now 2 places must be updated if/when deps change.

**Comment by greghendershott** [comment]
p.s. An example of how it fails: https://github.com/greghendershott/aws/runs/1455055421?check_suite_focus=true

**Comment by Bogdanp** [comment]
I think you want just `raco pkg install --auto`, rather than `raco pkg install --auto --link aws` because the `info.rkt` with the dependency information is in the root of your repository, not in `/aws`. So

```yml
      - name: Install Dependencies b/c info.rkt deps being ignored
        run: raco pkg install --auto sha http
      - name: Install Package
        run: raco pkg install --auto --link aws
```

should be

```yml
      - name: Install Package
        run: raco pkg install --auto
```
