### ISSUE TITLE
Need sudo?

### ISSUE THREAD

**Issue by pmatos** [Bogdanp/setup-racket#2]
Inside a container running `setup-racket@v0.5` fails because it needs sudo:
```
Run Bogdanp/setup-racket@v0.5
4s
##[error]Node run failed with exit code 1
Run Bogdanp/setup-racket@v0.5
  with:
    architecture: x64
    distribution: full
    variant: CS
    version: 7.5
/usr/bin/docker exec  8262b04fa2819cf254ffc9a602f0c652e98314195481043050c794007455f33b sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
sh /tmp/install-racket.sh
/tmp/install-racket.sh: 4: /tmp/install-racket.sh: sudo: not found
##[error]The process 'sh' failed with exit code 127
##[error]Node run failed with exit code 1
```

**Comment by pmatos** [comment]
The job looks like:

```
jobs:
  buildtest:

    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update 
        apt-get install -y cmake ninja-build gcc gcc-8 g++ g++-8
    - uses: Bogdanp/setup-racket@v0.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '7.5'
```
