### ISSUE TITLE
[Request] Make setup-rakcet compatible with caching 

### ISSUE THREAD

**Issue by ctittel** [Bogdanp/setup-racket#38]
My github action yml file includes the following two steps (purpose being that downloading and setting up the dependencies takes ~2 Minutes and I want to speed it up):

```yml
    - name: Cache Racket dependencies
      uses: actions/cache@v2
      with:
        path: /opt/racket
        key: ${{ runner.os }}-racket
    - name: Install Racket & dependencies 
      uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.1'
        packages: 'pollen, gregor, sugar, txexpr' # must be a comma-separated string!
        dest: '/opt/racket'
```

The caching part seems to work - after the first run of the action I was informed that 200MB were cached.

On the second run the step `Cache Racket dependencies` reported that 200MB were successfully restored.
However, the action got stuck for > 3 Minutes in the step `Install Racket & dependencies`.
I aborted the action and the log of `Install Racket & dependencies` contains the following:
```
  installerURL = https://download.racket-lang.org/installers/8.1/racket-8.1-x86_64-linux-cs.sh
  sh /tmp/install-racket.sh
  /usr/bin/sudo
  This program will extract and install Racket v8.1.
  
  Note: the required diskspace for this installation is 658M.
  
  
  Checking the integrity of the binary archive... ok.
  "/opt/racket" exists, delete? 
  Error: The operation was canceled.
```

It seems the prompt `"/opt/racket" exists, delete?` appeared and it didn't continue on its own.
