### ISSUE TITLE
feature request: installing in a different location

### ISSUE THREAD

**Issue by samth** [Bogdanp/setup-racket#8]
I would like to install both Racket BC and Racket CS in the same action, so probably the best way to do that is to install either with a different prefix, or using a self-contained install (not Unix-style) somewhere.

**Comment by Bogdanp** [comment]
You should now be able to do something like

```
- uses: Bogdanp/setup-racket@v0.9
  with:
    variant: 'regular'
    dest: '/opt/racketbc'
- uses: Bogdanp/setup-racket@v0.9
  with:
    variant: 'CS'
    dest: '/opt/racketcs'
```

And it'll install both variants in their respectiv `dest` paths. For now, this only works on Linux. It'd be easy to add support for mac as well, but less so for Windows.
